name: docker-build

on:
  repository_dispatch:
    types: [ publish-event ]
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.8.0
        with:
          access_token: ${{ github.token }}
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: core01/altaysorbent-website:latest
          build-args: |
            NEXT_PUBLIC_API_URL=https://api.altaysorbent.org
            NEXT_PUBLIC_DOMAIN_URL=https://altaysorbent.org
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
